### ISSUE TITLE
Improve the UI of Resources Section

### ISSUE THREAD

**Issue by diksha0149** [yashikabhargava/WebX#100]
## Description
A clear and concise description of what is the problem/issue in the website.
   In Resource section, margin and hover effect is not proper

## Screenshots
Put any screenshot(s) here.
![Screenshot (318)](https://user-images.githubusercontent.com/82230512/194940862-32962755-712b-4004-b4d7-0b381050dd76.png)

## Do you want to work on this issue?
Yes

## How are you planning to resolve on this issue?
I add some css to make better UI

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@diksha0149 assigning this issue to you.
