### ISSUE TITLE
Implementing frontend input validation on the contact form. 

### ISSUE THREAD

**Issue by centurion6x** [yashikabhargava/WebX#102]
## Description
Input to the contact form (i.e. telephone, email) must be validated in the frontend. 

## Screenshots
![image](https://user-images.githubusercontent.com/80505101/195013338-3b50ff89-8550-407c-b8ee-3264b2bbb564.png)

## Do you want to work on this issue?
I do want to work on this issue. 

## How are you planning to resolve on this issue?
Changes will be made to the contact.html file, mainly adding validation. 
I'm aware that this is a frontend-only project at the current time, but validation will be necessary if and when it's connected to a backend that accepts messages. 

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@centurion6x You can go ahead and work on this issue.

**Comment by centurion6x** [comment]
I've already implemented the validation for the contact form. But for the telephone number input, I think it'll be better to implement the field allowing the user to select the country with a drop-down. However, because that will be a fair about of additional code, I feel like I should raise another issue for it. Do you think that will be ok with Hacktoberfest rules? 

###Screenshots of the current state. 

![Screenshot 2022-10-14 at 09-35-36 WebX](https://user-images.githubusercontent.com/80505101/195762376-955fc147-76c0-452f-9ab1-da9ad9f9f5d3.png)


![Screenshot 2022-10-14 at 09-35-23 WebX](https://user-images.githubusercontent.com/80505101/195762410-f1dba66d-23d8-4df3-b156-9a392d7334a5.png)


![Screenshot 2022-10-14 at 09-35-03 WebX](https://user-images.githubusercontent.com/80505101/195762487-d70716ac-455e-44c3-8521-a1d7e752aff9.png)


![Screenshot 2022-10-14 at 09-34-44 WebX](https://user-images.githubusercontent.com/80505101/195762508-7b4d9b5c-8dc4-48f4-989d-18847be69b31.png)


![Screenshot 2022-10-14 at 09-34-26 WebX](https://user-images.githubusercontent.com/80505101/195762528-992a0b4f-ea9f-4843-b1e3-580cac2fc994.png)

**Comment by yashikabhargava** [comment]
> I've already implemented the validation for the contact form. But for the telephone number input, I think it'll be better to implement the field allowing the user to select the country with a drop-down. However, because that will be a fair bit of additional code, I feel like I should raise another issue for it. Do you think that will be ok with Hacktoberfest rules?


@centurion6x Yes, you can raise another issue for it.

**Comment by centurion6x** [comment]
Thank you. will do so.
