### ISSUE TITLE
Favicon not displaying

### ISSUE THREAD

**Issue by notafk-rajat** [yashikabhargava/WebX#104]
## Description
Seems like someone messed up the favicon image path a little while making a PR

## Screenshots
<img width="176" alt="Screenshot 2022-10-12 134221" src="https://user-images.githubusercontent.com/84857474/195287806-91657326-09e3-4457-932e-617c26084b84.png">

## Do you want to work on this issue?
Yes.
## How are you planning to resolve on this issue?
I'll just fix the favicon path, how it should be.

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by notafk-rajat** [comment]
I have seen issue #86, but we don't need to add a new favicon when we already have one. We just need to fix the path.

**Comment by yashikabhargava** [comment]
@notafk-rajat Have assigned this issue to you but I won't be able to consider it under hacktoberfest as it's mentioned on the hacktoberfest website that fixing broken images will not be counted as a contribution towards hacktoberfest.

**Comment by notafk-rajat** [comment]
Sure no problem, I'll fix it in a jiffy.
