### ISSUE TITLE
Improving text alignment on home page.

### ISSUE THREAD

**Issue by notafk-rajat** [yashikabhargava/WebX#106]
## Description
Currently, the text on the homepage is just right next to social icons, there should be a breathing space between the both.

## Screenshots
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/84857474/195380409-7c5253fc-1b89-4492-b73b-f0c8d4ad2adb.png">

## Do you want to work on this issue?
YES

## How are you planning to resolve on this issue?
I'll align the text slightly towards the right so that it has some space and looks better.

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@notafk-rajat you can go ahead and work on this issue.
