### ISSUE TITLE
Path not set correctly

### ISSUE THREAD

**Issue by MD-ARBAB-SAHID** [yashikabhargava/WebX#109]
## Description
The path to the index.html file is not set correctly in resources.html

## Screenshots
https://user-images.githubusercontent.com/63171580/195417210-859b38e0-6e52-4237-9774-5b6a5e67dafd.mov

## Do you want to work on this issue?
Yes.

## How are you planning to resolve on this issue?
By setting correct path to index.html file.

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by MD-ARBAB-SAHID** [comment]
@yashikabhargava can you please assign this to me?

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID You can work on this issue.
