### ISSUE TITLE
The text "SOME FREE RESOURCES for your next web development project" is not visible in light and dark mode

### ISSUE THREAD

**Issue by Akash7649** [yashikabhargava/WebX#113]
![Screenshot (294)](https://user-images.githubusercontent.com/101036630/195679083-0a361474-d518-48cf-95c3-b63766ac81e8.png)

I would like to solve this issue, so please assign this to me under hacktoberfest

**Comment by MD-ARBAB-SAHID** [comment]
@Akash7649 This issue has already been raised #112 .

**Comment by Akash7649** [comment]
But the text is not visible @MD-ARBAB-SAHID
