### ISSUE TITLE
Cards in the resource page squeezed

### ISSUE THREAD

**Issue by MD-ARBAB-SAHID** [yashikabhargava/WebX#123]
## Description
Cards in the resource page is not as same width as compared to cards in the actuals resources section(like css generators, icons).

## Screenshots
<img width="1438" alt="Screenshot 2022-10-18 at 1 53 20 PM" src="https://user-images.githubusercontent.com/63171580/196377890-dfcf6ed7-cdb8-4c35-9340-e8bcb1ead5ba.png">

<img width="1438" alt="Screenshot 2022-10-18 at 1 53 37 PM" src="https://user-images.githubusercontent.com/63171580/196377900-dff871b3-fe1f-481e-9ad4-3dabc993e8eb.png">

## Do you want to work on this issue?
Yes

## How are you planning to resolve on this issue?
By setting card of equal size using bootstrap.

## Are you raising this issue under hacktoberfest?
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID I do not feel the need of it, hence closing this issue.

**Comment by MD-ARBAB-SAHID** [comment]
> @MD-ARBAB-SAHID I do not feel the need of it, hence closing this issue.



> @MD-ARBAB-SAHID I do not feel the need of it, hence closing this issue.

👍
