### ISSUE TITLE
Adding icons8 to icons list

### ISSUE THREAD

**Issue by MonicaFidalgo** [yashikabhargava/WebX#127]
## Description
I would like one more free icons resources to the website (icons8)

## Screenshots
![Captura de ecrã 2022-10-20, às 12 42 39](https://user-images.githubusercontent.com/41929489/196939497-618d8517-6ff4-4064-b1a4-0ec40a42fcbe.png)

## Do you want to work on this issue?
Yes

## How are you planning to resolve on this issue?
Adding a new card following the same card rules

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@MonicaFidalgo Yes, you can work on this issue.

**Comment by MonicaFidalgo** [comment]
Thank you @yashikabhargava :) created a pr [here](https://github.com/yashikabhargava/WebX/pull/128)
