### ISSUE TITLE
Make the nav-bar anchored

### ISSUE THREAD

**Issue by centurion6x** [yashikabhargava/WebX#134]
## Description
While scrolling the vertical navbar gets scrolled up. Anchoring the nav-bar will make navigation easier. 

## Screenshots
![image](https://user-images.githubusercontent.com/80505101/197946279-7af0c7ee-d521-4bbc-b061-18729e2e4c27.png)
![image](https://user-images.githubusercontent.com/80505101/197946456-c24c6c61-db7c-4dc5-9267-841e7aee6125.png)

## Do you want to work on this issue?
Yes

## How are you planning to resolve on this issue?
Editing the HTML of nav-bar to make it stable. 

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@centurion6x You can work on this.
