### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by santhos-13** [yashikabhargava/WebX#149]
## Description
resource underflow content gets hidden/collides with the main page content

## Screenshots
![image](https://user-images.githubusercontent.com/105668165/200869469-c781e7f1-c272-431f-9df6-5e55d356ad94.png)

## Do you want to work on this issue?
 yes 

## How are you planning to resolve on this issue?
i will make the content of resources to z-index 1.

@yashikabhargava

**Comment by yashikabhargava** [comment]
@santhos-13 you can work on this issue.
