### ISSUE TITLE
Create navigation for resources in header

### ISSUE THREAD

**Issue by yashikabhargava** [yashikabhargava/WebX#19]
Create navigation to reach particular resources quickly.

**Comment by Heismanish** [comment]
Hey, I would like to do this.

**Comment by harsitagarwalla187** [comment]
it already has a navbar . What more do we have to add?

**Comment by yashikabhargava** [comment]
under resources, a further dropdown menu can be added to access particular resources quickly. Like -
- Icons
- Ui illustration
- CSS generators 
 and so on

**Comment by yashikabhargava** [comment]
@harsitagarwalla187 Okay, I'm assigning it to you.

**Comment by harsitagarwalla187** [comment]
@yashikabhargava  Okay

**Comment by harsitagarwalla187** [comment]
@yashikabhargava  you assigned it to Heismanish

**Comment by yashikabhargava** [comment]
Yes, I'm sorry I mentioned you by mistake. Assigned it to him because he asked first.

**Comment by harsitagarwalla187** [comment]
Okay

**Comment by Heismanish** [comment]
@yashikabhargava, check this out please.
![Screenshot from 2022-10-03 12-54-13](https://user-images.githubusercontent.com/92051445/193522179-d07fd805-4437-4021-8b7a-a1fb4c4caa2c.png)

**Comment by Heismanish** [comment]
@yashikabhargava  here it is, check it out.
![Screenshot from 2022-10-03 13-23-17](https://user-images.githubusercontent.com/92051445/193527196-aa7bdfb7-7a12-44f9-b856-893390452f7b.png)

**Comment by yashikabhargava** [comment]
Looking great but please make the dropdown appear under resources and remove the menu as there is no need for that.
Thanks

**Comment by Heismanish** [comment]
@yashikabhargava have a look, is it better now. 
![Screenshot from 2022-10-03 16-23-33](https://user-images.githubusercontent.com/92051445/193560741-7fde7c7e-ac92-4ef0-ba20-2f7a8fc62957.png)

**Comment by yashikabhargava** [comment]
Yes, looking great. You can go ahead and open a PR.

**Comment by yashikabhargava** [comment]
@Heismanish you closed the PR, are you not working on this issue anymore?

**Comment by yashikabhargava** [comment]
Okay, So you are going to open a new PR?

**Comment by Heismanish** [comment]
Sorry I won't be able to do so, because there are some new code has been inserted in the css that's making the navigation button that I added beahve absurdly and I don't have an idea about how to fix so please assign it to someone else.

**Comment by yashikabhargava** [comment]
Sure, No problem.

**Comment by Laxmankohar** [comment]
@yashikabhargava  can you please assign this to me? I want to work on this.

**Comment by yashikabhargava** [comment]
@Laxmankohar Yes, assigning it to you.

**Comment by yashikabhargava** [comment]
Yes, looks great! You can go ahead and open a PR.
