### ISSUE TITLE
Make landing page image respsonsive

### ISSUE THREAD

**Issue by yashikabhargava** [yashikabhargava/WebX#20]
When the screen size goes below 500px, the landing page image is not completely visible, so make it responsive.
![Capture](https://user-images.githubusercontent.com/76060661/193464954-988383ce-c42b-4d84-8a89-9d1dfa5a6178.PNG)

**Comment by yesimhozman** [comment]
can you assign it to me ? I want to make contribution

**Comment by yashikabhargava** [comment]
Sure, You can go for it.

**Comment by yesimhozman** [comment]
Is it okay to use bootstrap ?

**Comment by yashikabhargava** [comment]
Yes, You can use bootstrap.

**Comment by yesimhozman** [comment]
thanks
