### ISSUE TITLE
Make landing page text responsive

### ISSUE THREAD

**Issue by yashikabhargava** [yashikabhargava/WebX#21]
When reducing the screen size, the size of the text on the landing page remains the same, make it responsive to make the website suitable for all screen sizes.
![Capture](https://user-images.githubusercontent.com/76060661/193465389-db1ee1a3-645e-4773-adb4-13a489d54e8a.PNG)

**Comment by harsitagarwalla187** [comment]
Please assign it to me.

**Comment by yashikabhargava** [comment]
Okay, Assigning it to you.

**Comment by harsitagarwalla187** [comment]
![Screenshot (53)](https://user-images.githubusercontent.com/84774840/193466941-5b981eb8-d7b1-476b-b859-26d4dcb37301.png)
Is it ok?

**Comment by yashikabhargava** [comment]
Yes the text looks fine but I'm not able to see the get started button, Where did that go?

**Comment by harsitagarwalla187** [comment]
Ok let try to solve that also.

**Comment by harsitagarwalla187** [comment]
![Screenshot 2022-10-02 225018](https://user-images.githubusercontent.com/84774840/193467338-6aab384a-e287-4820-ba26-7dfba6072d42.png)

**Comment by yashikabhargava** [comment]
Looking good, you can go head and make a PR.

**Comment by harsitagarwalla187** [comment]
Ok thank you
