### ISSUE TITLE
Make get started button on landing page responsive 

### ISSUE THREAD

**Issue by yashikabhargava** [yashikabhargava/WebX#22]
![Capture](https://user-images.githubusercontent.com/76060661/193465672-79637975-da14-47be-929c-0c30eb0b8eae.PNG)

**Comment by then00bprogrammer** [comment]
assign it to me

**Comment by piyush362** [comment]
can i do this ?

**Comment by yashikabhargava** [comment]
@then00bprogrammer any update? kindly reply by end of the day else I'll be assigning it to @piyush362 .

**Comment by yashikabhargava** [comment]
No problem.
