### ISSUE TITLE
Add new feature: Follow Us/Share Us button

### ISSUE THREAD

**Issue by grraghav120** [yashikabhargava/WebX#26]
We can add Follow Us buttons on various Social media platforms
Buttons like:
Facebook
Twitter
Linkedin etc

If you like my idea kindly assign this issue to me i can add this new feature under hacktoberfest-accepted label

**Comment by yashikabhargava** [comment]
Yes, Assigning this to you, and thank you for submitting your issue.

**Comment by grraghav120** [comment]
Okay i am working on this..
Kindly add one more label as HACKTOBERFEST-ACCEPTED Thank you.

**Comment by yashikabhargava** [comment]
@grraghav120 That label is for PRs, I'll add it to your PR once it's merged.
