### ISSUE TITLE
Make Contact Us Section UI better

### ISSUE THREAD

**Issue by sujay26p** [yashikabhargava/WebX#27]
Alignment of the Contact Us labels looks bit different from the text box below so planning to align them to the left along with some background to the contact Us section. Looking to change Submit shape similar to above text fields.

**Comment by yashikabhargava** [comment]
Okay, assigning this issue to you. Please use the PR template provided when you open a PR and Thank you for submitting your issue.

**Comment by sujay26p** [comment]
@yashikabhargava  Thanks for assigning the issue and can you please add the label hacktober as well, i will be contributing under it.
