### ISSUE TITLE
Make navbar look good in mobile devices

### ISSUE THREAD

**Issue by piyush362** [yashikabhargava/WebX#29]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/62232366/193566786-3e7e2e74-0811-4645-ab3e-f8cb1bc812b9.png">

**Comment by yashikabhargava** [comment]
Thank you for submitting the issue, do you want to work on it?

**Comment by sarthakastic** [comment]
I want to work on this issue. Please assign it to me.

**Comment by piyush362** [comment]
> Thank you for submitting the issue, do you want to work on it?

yes i want to work, assign to me , please

**Comment by yashikabhargava** [comment]
@piyush362 okay, assigning it to you.
@sarthakastic Thank you for showing your interest, you can raise another issue and I'll assign that to you.

**Comment by piyush362** [comment]
Hey, it's done please checkout , and can you please add hacktoberfest label
