### ISSUE TITLE
Automate labeling of PRs and issues 

### ISSUE THREAD

**Issue by yashikabhargava** [yashikabhargava/WebX#33]
Automate the labeling of PRs and issues by creating labeler.yml under .github/ workflow.

some labels can be 

- hacktoberfest-accepted for PRs that are merged and were opened by hacktoberfest participants.
- Good-first-issue
- Enhancement 
- design
- hacktoberfest for issues raised by hacktoberfest participants.

more labels can be added but please ask for approval before adding.

**Comment by Aspireve** [comment]
Hey!! @yashikabhargava could I work on this?
Also could I know about how to distinguish between the different labels ie. How do I know if the PR is from a Hacktoberfest participant

**Comment by yashikabhargava** [comment]
I've added a question in the PR template, so it will be mentioned in the PR if the PR is under hacktoberfest. Maybe we can do something like if PR contains hacktobefest keyword then it will be labeled.

**Comment by Aspireve** [comment]
Hi @yashikabhargava I dont think ```labeler.yml``` works with keywords on the PR but instead it works with the files which are changed

**Comment by yashikabhargava** [comment]
Okay, I do not have much idea about it. What do you have in mind?

**Comment by Aspireve** [comment]
Kinda I too didnt understand much lol (just thought I could learn about it on the go).
Maybe someone who has already done it before can explain it better!!

**Comment by SajidAnTechie** [comment]
@yashikabhargava can I work on this issue?. If yes do assigne me

**Comment by jyotika6221** [comment]
Please assign me this issue. And share a brief detail about it.

**Comment by yashikabhargava** [comment]
@SajidAnTechie Yes, you can work on this issue.

**Comment by SajidAnTechie** [comment]
@yashikabhargava i have opened the pr for this issue. Please review
https://github.com/yashikabhargava/WebX/pull/90
