### ISSUE TITLE
Create a Page Up Scroll Button 

### ISSUE THREAD

**Issue by grraghav120** [yashikabhargava/WebX#34]
There is no Scroll Up button and having it makes the user's work easy and user friendly
Please assign me this under Hacktoberfest 2022
@yashikabhargava

**Comment by yashikabhargava** [comment]
Yes, that's a great suggestion. I'll assign it to you once your previous PR is merged.

**Comment by grraghav120** [comment]
Okay

**Comment by grraghav120** [comment]
Okay time to move on this issue :) @yashikabhargava
