### ISSUE TITLE
Improvement in design of contact form

### ISSUE THREAD

**Issue by Prashant7451** [yashikabhargava/WebX#35]
Contact form is quite old fashioned i want to redesign it

**Comment by yashikabhargava** [comment]
Please provide more information on the changes that you are planning on doing.

**Comment by Prashant7451** [comment]
The input box looks more large i will use bootstrap to  make it look more better

![0871b475-fd06-4f08-a3f3-9becf8ff019e](https://user-images.githubusercontent.com/103504965/193579820-e80cd17b-007e-477e-b212-d8a2ad664391.jpg)
Using this reference adding css bootstrap it will make contact form look more attractive

Using this reference

**Comment by yashikabhargava** [comment]
Okay, sounds good. Assigning it to you. Are you raising this issue under hacktoberfest?

**Comment by Prashant7451** [comment]
Should i pull request for change? I have completed it almost.

**Comment by Prashant7451** [comment]
Yes its under hacktoberfest

**Comment by Prashant7451** [comment]
Ya sure

**Comment by Prashant7451** [comment]
<img width="701" alt="ss" src="https://user-images.githubusercontent.com/103504965/193646655-a7ebc701-f7f4-432d-93e2-2d5e7ea0295b.png">

**Comment by yashikabhargava** [comment]
Looks good but the color of the button does not seem to be matching with the rest of the website. Also, the color of "Drop up a message" is a bit dark. Can you fix this and share the update again?
Thanks
