### ISSUE TITLE
Change the font and size of texts

### ISSUE THREAD

**Issue by akashyap25** [yashikabhargava/WebX#36]
The font is not well designed and size of texts are uneven , I can improve this , please assign it to me.

**Comment by yashikabhargava** [comment]
Can you please provide more information on which section's font size you are talking about? Also, what are the changes that you are planning?

**Comment by akashyap25** [comment]
* The logo text should be bolder with a good font 
* The nav-bar texts are very small 
* all the for texts(e.g. for icons ) needs a bit top and bottom padding and better font style

**Comment by yashikabhargava** [comment]
Okay, assigning it to you. Are your creating this issue under hacktoberfest?

**Comment by akashyap25** [comment]
> Okay, assigning it to you. Are your creating this issue under hacktoberfest?

Yes
