### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by notafk-rajat** [yashikabhargava/WebX#37]
Since there is no favicon currently we can put one there.
This issue is opened under Hacktoberfest.

**Comment by Rashmisingh-18** [comment]
Please assign this issue to me.
Want to add this as favicon: https://img.icons8.com/stickers/2x/developer-mode.png

**Comment by notafk-rajat** [comment]
This issue is not yet validated by the owner of the repository, I just noticed something that should be there and mentioned it.

**Comment by yashikabhargava** [comment]
@notafk-rajat Yes, that's a great suggestion. Do you want to work on this issue? If yes then please provide more information about favicon you want to add.

**Comment by yashikabhargava** [comment]
@Rashmisingh-18 Thank you for showing your interest, If @notafk-rajat will not be working on this issue then I'll assign it to you and If he's going to work on the issue then you can raise another issue, I'll assign that to you : )

**Comment by notafk-rajat** [comment]
@yashikabhargava Yep would like to work on the issue. 

I would like to add this favicon 

![icons8-repository-48](https://user-images.githubusercontent.com/84857474/193605306-fa0c1582-9a35-4721-a11f-104c15d542a2.png)

As it kind of matches the theme of the website.

**Comment by yashikabhargava** [comment]
Okay, The favicon looks good. I'm assigning the issue to you.

**Comment by notafk-rajat** [comment]
Should  I save the favicon image in img->icons ?

**Comment by yashikabhargava** [comment]
@notafk-rajat Are you raising this issue under hacktoberfest?

**Comment by notafk-rajat** [comment]
@yashikabhargava Yes

**Comment by yashikabhargava** [comment]
> Should I save the favicon image in img->icons ?

No, that folder is for resources related to the icons tool. You can save the image just inside the img folder by the name of favicon.

**Comment by notafk-rajat** [comment]
Okay.
