### ISSUE TITLE
Hovering on Navbar button seems ugly

### ISSUE THREAD

**Issue by suvasreeMondalDev** [yashikabhargava/WebX#42]
## Description
On hovering Navbar button, background color too big without any effect.

## Screenshots
![image](https://user-images.githubusercontent.com/114935019/193618906-6d86f03f-7ee8-4601-abcf-75a3eae1177c.png)

## Do you want to work on this issue?
I want to work on this issue, please assign this to me. I'll do it definitely. 

## How are you planning to resolve on this issue?
I'll check for the padding or margin of navbar button and I'll reduce that.

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by suvasreeMondalDev** [comment]
or please add a hacktoberfest label on this project

**Comment by yashikabhargava** [comment]
> or please add a hacktoberfest label on this project

Hcktoberfest label is added on the project : )

**Comment by Sammydepoj** [comment]
hi, i would like to work on this

**Comment by Sammydepoj** [comment]
alright then. thank you
