### ISSUE TITLE
Animating the Web-X Logo on Hover 

### ISSUE THREAD

**Issue by sakshamvedi** [yashikabhargava/WebX#43]
I want to animate the web-x logo on header screen of (home screen) ,that  animate on **hover ** by cursor,

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by sakshamvedi** [comment]
Hacktoberfest-2022

**Comment by yashikabhargava** [comment]
Sounds great, assigning this issue to you.
