### ISSUE TITLE
Add dark theme toggle button on website

### ISSUE THREAD

**Issue by Laxmankohar** [yashikabhargava/WebX#47]
I want to add a dark theme toggle button on website at the bottom of page.

## Do you want to work on this issue?
 yes 

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
Sounds good, you can go ahead and work on this issue.

**Comment by Laxmankohar** [comment]
ok
