### ISSUE TITLE
Sticky navbar

### ISSUE THREAD

**Issue by Prashant7451** [yashikabhargava/WebX#49]
## Description
navbar doesn't remain static as we move the site's page

## Do you want to work on this issue?
write yes 

## How are you planning to resolve on this issue?
I will make navbar static which makes it more effective.

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
I do not feel the need for making the footer static but would like to work on a sticky nav instead.

**Comment by Prashant7451** [comment]
Okay sounds cool,so should i change footer to navbar or create a new issue

**Comment by yashikabhargava** [comment]
No, You can edit this issue only, and then I'll assign it to you.

**Comment by yashikabhargava** [comment]
Also, please complete the tasks mentioned in the previous issue you raised and update the PR that you have open, and then only start working on this one.
Thanks

**Comment by Prashant7451** [comment]
i have made pr actually u excepted pr so it was showing conflict now it is ressolved u can check and merge the same.

**Comment by yashikabhargava** [comment]
Yes, I saw that and have asked you to make some changes please check that out.

**Comment by Prashant7451** [comment]
ya sure

**Comment by Prashant7451** [comment]
Hey @yashikabhargava  assign this task so that i may work on it under hacktoberfest

**Comment by Prashant7451** [comment]
@yashikabhargava  do you need sticky navbar
