### ISSUE TITLE
Add a zoom in effect to the cards when they are hovered upon.

### ISSUE THREAD

**Issue by shashank-iter** [yashikabhargava/WebX#50]
## Description
The key idea is to add a zoom in effect on the cards when they are hovered upon

## Screenshots 
I will attach them before making a pull request.

## Do you want to work on this issue?
Yes I do want to work this issue.

## How are you planning to resolve on this issue?
I will use CSS transform transform properties.

## Are you raising this issue under hacktoberfest? 
Yes.

**Comment by yashikabhargava** [comment]
Sounds good, You can go ahead and work on this issue.

**Comment by shashank-iter** [comment]
@yashikabhargava Here is a preview of the changes that I made:
https://clipchamp.com/watch/acMAh8XmBB7
