### ISSUE TITLE
Animate elements as they scroll into view.

### ISSUE THREAD

**Issue by abhirk247** [yashikabhargava/WebX#58]
## Description
Animate elements as they scroll into view.

## Screenshots

https://user-images.githubusercontent.com/41264611/193790385-8672618f-c9ae-4e62-b81e-d6621640b44a.mp4

## Do you want to work on this issue?
yes

## How are you planning to resolve on this issue?
using ScrollReveal javascript library.

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@abhirk247 This looks great, you can go ahead and open a PR.
