### ISSUE TITLE
Website not responsive in tablets

### ISSUE THREAD

**Issue by MD-ARBAB-SAHID** [yashikabhargava/WebX#62]
## Description
The content of the website overflows and breaks down at certain breakpoints(usually for tablets sizes ranging from 600 - 800)

## Screenshots
<img width="694" alt="Screenshot 2022-10-04 at 11 38 52 PM" src="https://user-images.githubusercontent.com/63171580/193895083-9b847c89-91db-410c-ade0-95093258252b.png">

<img width="707" alt="Screenshot 2022-10-04 at 11 39 16 PM" src="https://user-images.githubusercontent.com/63171580/193895118-c70c310f-a9e3-4474-8c96-db43cd9772ee.png">

## Do you want to work on this issue?
Yes

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by MD-ARBAB-SAHID** [comment]
Can be solved by using bootstrap cards.Can you assign this to me ?

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID Okay, assigning this issue to you.

**Comment by MD-ARBAB-SAHID** [comment]
For large screen size (>=992px) 3 cards in a row
For medium screen size(>=768px) 2 cards in a row
For small screen size(>=576px) 1 cards in a row

Is that fine ?

**Comment by yashikabhargava** [comment]
Yes, It's fine.

**Comment by MD-ARBAB-SAHID** [comment]
ok opening a PR @yashikabhargava
