### ISSUE TITLE
Follow Us Buttons

### ISSUE THREAD

**Issue by notafk-rajat** [yashikabhargava/WebX#63]
## Description
The follow us buttons in the footer sections are not directing to the link they should as the links are not provided, on clicking them one just goes back to the top of the page.

## Do you want to work on this issue?
Yes

## How are you planning to resolve on this issue?
I'll add the proper links to all three buttons.
I'll need the link for linkdin though @yashikabhargava 

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes

**Comment by tajbaba999** [comment]
I want to work on this issue.
Should I add any social media buttons
1)Facebook.
2)Instagram
3)other
I know how to add them can please assign me to this project

**Comment by notafk-rajat** [comment]
@tajbaba999 The issue is not about adding buttons, it's about adding relevant links to the existing buttons. Also as I already stated above that I do want to work on this issue. Hope you understand.

**Comment by grraghav120** [comment]
I leave that links empty because It will be added by @yashikabhargava from her side.

**Comment by yashikabhargava** [comment]
@notafk-rajat Okay, Assigning this issue to you. Here's the link to my LinkedIn profile - http://www.linkedin.com/in/yashika-bhargava-1171581aa

**Comment by tajbaba999** [comment]
Thanks for your replay @notafk-rajat 
Can you please assign me this task? I am ready to do this job.

**Comment by yashikabhargava** [comment]
@tajbaba999 Thank you for showing your interest but this issue has already been assigned. You can raise some other issue and I'll assign that to you.
