### ISSUE TITLE
Changing the Readme.md file

### ISSUE THREAD

**Issue by grraghav120** [yashikabhargava/WebX#64]
## Description
Changing the Readme.md file mainly the screenshots of website (modified website)

## Screenshots
Put any screenshot(s) here.

## Do you want to work on this issue?
Yes

## How are you planning to resolve on this issue?
Changing the screenshots

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
I'll assign this issue to you but won't be able to consider it under hacktoberfest as it's mentioned on hacktoberfest website that optimizing images won't be counted as a contribution towards hacktoberfest.

**Comment by grraghav120** [comment]
Okay np @yashikabhargava
