### ISSUE TITLE
Contact Page looks not good according to other elements in website

### ISSUE THREAD

**Issue by grraghav120** [yashikabhargava/WebX#67]
## Description
want to change contact page according to the elements of website give me suggestion as how to improve.

## Screenshots
Put any screenshot(s) here.
![image](https://user-images.githubusercontent.com/96789493/194063451-2cb06a82-3579-43d6-9183-a7fea9d9fc05.png)
Like this as made some changes 

## Do you want to work on this issue?
YES

## How are you planning to resolve on this issue?
Do some changes regarding contact form

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@grraghav120 This issue has already been raised and is assigned to someone else.
