### ISSUE TITLE
Logo animation flickering

### ISSUE THREAD

**Issue by MD-ARBAB-SAHID** [yashikabhargava/WebX#69]
## Description
Logo animation keeps flickering when hovered on edge of logo.

## Screenshots

https://user-images.githubusercontent.com/63171580/194100530-b9e6a78e-3dfe-4cfd-84ba-210ad1bd1edc.mov

## Do you want to work on this issue?
No

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
Okay, Assigning this to you. Would you also like to work on making the animation better as it doesn't look good?

**Comment by yashikabhargava** [comment]
One suggestion, please remove that border and background and do the animation just on text.
Thanks

**Comment by MD-ARBAB-SAHID** [comment]
so you only want the text to rotate 360 deg ? @yashikabhargava

**Comment by yashikabhargava** [comment]
> so you only want the text to rotate 360 deg ? @yashikabhargava 
No, instead of rotating it, can we not do something else?

**Comment by MD-ARBAB-SAHID** [comment]
I Am on it, will let you know.

**Comment by MD-ARBAB-SAHID** [comment]
Normal animation without hovering
https://user-images.githubusercontent.com/63171580/194123311-a66c3eae-2272-464b-87b6-75e95050b9f1.mov

**Comment by yashikabhargava** [comment]
I'm not sure about having that animation for all time.

**Comment by MD-ARBAB-SAHID** [comment]
okay let me check some other animations

**Comment by MD-ARBAB-SAHID** [comment]
What about using a logo image instead of normal text ? Will that be fine ?

**Comment by yashikabhargava** [comment]
Yes, that'll be fine.

**Comment by MD-ARBAB-SAHID** [comment]
![WebX-logos](https://user-images.githubusercontent.com/63171580/194425339-4fa8249c-7be2-4359-9fd1-a07fb1da3efa.jpeg)
2.

![WebX-logos_white](https://user-images.githubusercontent.com/63171580/194425371-f3d1a2d6-86b2-4888-8b43-fac860ba457f.png)

3.

![WebX-logos_black](https://user-images.githubusercontent.com/63171580/194425402-7362ad78-5302-4830-9776-d1fd8227369a.png)

4.

![WebX-logos_transparent](https://user-images.githubusercontent.com/63171580/194425424-2e263938-63cd-4772-9654-5aff5101cd78.png)

5.

![WebX -1](https://user-images.githubusercontent.com/63171580/194425490-52200856-6738-459b-96da-a5736467dfc0.jpg)

6.

![WebX-logos](https://user-images.githubusercontent.com/63171580/194425563-c49646bf-e6e9-4525-8ab8-8ae2784c9ab6.jpeg)

7.

![WebX-logos_white](https://user-images.githubusercontent.com/63171580/194425649-322433fa-c71d-4e79-960e-108c91d389c2.png)

8.

![WebX-logos_transparent](https://user-images.githubusercontent.com/63171580/194425680-432eee8b-f884-4e36-b36f-7348c6159bf5.png)

9.


![WebX-logos_black](https://user-images.githubusercontent.com/63171580/194425926-79ed016f-86b4-4aa2-9bdf-12fd432b82f9.png)

10.



![WebX-logos](https://user-images.githubusercontent.com/63171580/194426003-987ead7e-1096-4d94-bc34-e0bda5398334.jpeg)


11.


![WebX-logos](https://user-images.githubusercontent.com/63171580/194426508-0d68ed63-0700-4f5e-8b99-c9c58a0d3b5c.jpeg)


12.



![WebX-logos_white](https://user-images.githubusercontent.com/63171580/194426525-9ef705cc-c636-4a9a-9b24-ee26e71e3e41.png)

@yashikabhargava

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID The second one looks fine, But please don't open a PR yet as you know some changes are being made to the code.

**Comment by MD-ARBAB-SAHID** [comment]
Sure np. Just remind whenever I have to open a PR. @yashikabhargava

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID You can open a PR now.

**Comment by MD-ARBAB-SAHID** [comment]
<img width="1435" alt="Screenshot 2022-10-09 at 1 54 36 PM" src="https://user-images.githubusercontent.com/63171580/194746128-66d09c0a-e390-4112-accc-56410f70679f.png">

@yashikabhargava as background is white so I added the black one(3rd)

**Comment by MD-ARBAB-SAHID** [comment]
@yashikabhargava is it fine ? Shall I open a PR.

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID In dark mode, the black one won't be visible and according to the theme, the logo color is blue.
 Hence you do one thing just solve the flickering logo issue and open the PR. I apologize for the inconvenience.

**Comment by MD-ARBAB-SAHID** [comment]
@yashikabhargava We can also add a logo with white text and render one of them depending on the mode.
Shall I try that one ?

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID I actually want the color of the logo to remain as it is now only i.e. blue.

**Comment by MD-ARBAB-SAHID** [comment]
@yashikabhargava sure I will remove the flickering issue and will open a PR.
