### ISSUE TITLE
Adding New Resources.

### ISSUE THREAD

**Issue by OgaDavid** [yashikabhargava/WebX#71]
Adding more resources to the resources section.

## Do you want to work on this issue?
 yes 

## How are you planning to resolve on this issue?
- To the Icons section, I'll be adding [Iconoir](https://iconoir.com/) (An  Icons library available in SVG format for React and React Native libraries, flutter, figma and framer)
- To the CSS generator section. i'll be adding [Fffuel](https://fffuel.co/uuundulate/) (An amazing svg generator for background patterns)
- I also want to add a "UI UX  Design" Section in the resources section where i'll be adding resources like 
🎯[3d icons](https://3dicons.co/) (An open source 3d icons library that can be used with any design tool), 
🎯[Artboard Studio](https://artboard.studio/) (An amazing library for animated mockups)

## Do you want to raise this under hacktoberfest?
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
Sounds good, assigning this issue to you.

**Comment by OgaDavid** [comment]
Ok, thanks you.

**Comment by OgaDavid** [comment]
Hello @yashikabhargava , I've made the changes.

**Comment by OgaDavid** [comment]
![webx-4-edit](https://user-images.githubusercontent.com/104001201/194273954-f7fb13ff-db0e-47f4-ba9e-b615a5b7db8b.png)

**Comment by yashikabhargava** [comment]
Yes, you can go ahead and open a PR.

**Comment by OgaDavid** [comment]
Thank you for merging my pull request, i really appreciate you!
