### ISSUE TITLE
Enhancement: Divide code into different sections for better readability and maintenance

### ISSUE THREAD

**Issue by ShubhamPatil0723** [yashikabhargava/WebX#73]
## Description
There are a lot of resources so if we divide these resources into different files then it will be easy to navigate and maintain code. 

## Screenshots
Add Category dropdown or menu in this nav bar
![category](https://user-images.githubusercontent.com/92074003/194160129-7ded749f-ad4b-4dea-bc55-b056e7097587.jpg)

## Do you want to work on this issue?
yes, Please assign this task to me @yashikabhargava 

## How are you planning to resolve this issue?
     - Divide code of different sections like icons, Illustrations, etc into different files
     - Route to them when the user clicks on that category(We can achieve this using JS )

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by MahijithMenon** [comment]
yes, Please assign this task to me @yashikabhargava

**Comment by yashikabhargava** [comment]
@ShubhamPatil0723 Thank you for raising this issue, I was about to do the same. Are you also going to work on the style.css file as currently, it is really hard to read the code in that file?

About the dropdown, that issue has already been raised and assigned to someone.

**Comment by MD-ARBAB-SAHID** [comment]
Is it like different pages for different sections ?@yashikabhargava

**Comment by ShubhamPatil0723** [comment]
@yashikabhargava Sure I can work on both Html and CSS, Btw should I wait till other PRs are merged or start right now? or else there will be conflicts between our PRs

**Comment by ShubhamPatil0723** [comment]
@MD-ARBAB-SAHID Yes, Code will get divided into different files

**Comment by MD-ARBAB-SAHID** [comment]
How it will look I mean the navbar and footer must be same and only the middle content will change ?

**Comment by ShubhamPatil0723** [comment]
@MahijithMenon You can check PR #75 he have posted some SS

**Comment by ShubhamPatil0723** [comment]
> How it will look I mean the navbar and footer must be same and only the middle content will change ?

yeah something like that

**Comment by MD-ARBAB-SAHID** [comment]
> > How it will look I mean the navbar and footer must be same and only the middle content will change ?
> 
> yeah something like that

In that case its going to be a lot of repetitive code.

**Comment by ShubhamPatil0723** [comment]
We can't do anything about that, If it was react we would have to just update some components but for HTML other than creating a new page there are no solutions in my mind, Do you have an alternate solution for this? @MD-ARBAB-SAHID

For CSS I can minimize the code by importing repetitive code into other CSS files

**Comment by MD-ARBAB-SAHID** [comment]
@ShubhamPatil0723 React would have been a perfect choice. Apart from that we can use templating language like EJS or Pug but that requires a Node Js server.

**Comment by ShubhamPatil0723** [comment]
Yeah but let's wait for yashika

**Comment by yashikabhargava** [comment]
> @yashikabhargava Sure I can work on both Html and CSS, Btw should I wait till other PRs are merged or start right now? or else there will be conflicts between our PRs

Yes maybe start tomorrow let me merge some PRs.

**Comment by yashikabhargava** [comment]
> Is it like different pages for different sections ?@yashikabhargava

Yes, that is the only solution with HTML.

**Comment by yashikabhargava** [comment]
> Yeah but let's wait for yashika

Actually, I want this repository to be beginner friendly, hence for now let's just go with HTML .

**Comment by ShubhamPatil0723** [comment]
Got it

**Comment by yashikabhargava** [comment]
@ShubhamPatil0723 You can start working from today only, I'm assigning this issue to you. 
Can you please tell though how long will it take you to make all these changes?

**Comment by ShubhamPatil0723** [comment]
> @ShubhamPatil0723 You can start working from today only, I'm assigning this issue to you. Can you please tell though how long will it take you to make all these changes?

I'm not sure if nothing comes up I can get it done by this Sunday

**Comment by yashikabhargava** [comment]
Alright!
