### ISSUE TITLE
What happen with My Code it does not show on your hosted website and also Contact Button also Disturbed and follow us button also disturbed kindly check

### ISSUE THREAD

**Issue by grraghav120** [yashikabhargava/WebX#79]
## Description
What happen with My Code it does not show on your hosted website and also Contact Button also Disturbed and follow us button also disturbed kindly check

## Screenshots
Put any screenshot(s) here.

## Do you want to work on this issue?
write yes or no

## How are you planning to resolve on this issue?
Provide some information about the changes you'll be doing to resolve the issue.

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by grraghav120** [comment]
![image](https://user-images.githubusercontent.com/96789493/194569021-23a6eee6-89d1-47f1-bde5-027be6fedaaf.png)

**Comment by yashikabhargava** [comment]
@grraghav120 Thank you for pointing this out, will look into that.

**Comment by MD-ARBAB-SAHID** [comment]
What is the desired result any screenshot ?@grraghav120 @yashikabhargava

**Comment by grraghav120** [comment]
Can i work on the issue on new branch? @yashikabhargava

**Comment by yashikabhargava** [comment]
@grraghav120 It is working now.
