### ISSUE TITLE
Add more names of GREAT COLORS TOOLS

### ISSUE THREAD

**Issue by heyvats21** [yashikabhargava/WebX#81]
## Description
Want to add more names of the colors tools.

## Screenshots
Put any screenshot(s) here
![image](https://user-images.githubusercontent.com/81029204/194607347-a756d4c5-e2fd-485e-afc8-1a941f5ef986.png)
.

## Do you want to work on this issue?
write yes

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by heyvats21** [comment]
Okayy @yashikabhargava

**Comment by jyotika6221** [comment]
Please assign me with this task.

**Comment by heyvats21** [comment]
@yashikabhargava is the updation part done?

**Comment by yashikabhargava** [comment]
@heyvats21 Yes, assigning this issue to you, please add free resources only.

**Comment by yashikabhargava** [comment]
@jyotika6221 this issue has been assigned, kindly raise some other issue, and I'll assign that to you.

**Comment by jyotika6221** [comment]
hey, i have already asked for assigning automate labelling PRs issue. kindly assign it to me.

**Comment by heyvats21** [comment]
@Saurav50 I am not getting what you have done??? I think this task was assigned to me and i have sent the merge request to @yashikabhargava

**Comment by diksha0149** [comment]
Hiii @yashikabhargava , I know some more  Color website, Please assign me this issue .

**Comment by heyvats21** [comment]
@diksha0149 i have added a lot of websites in it. but @yashikabhargava  has not updated it yet.

**Comment by yashikabhargava** [comment]
> Hiii @yashikabhargava , I know some more Color tool website, Please assign me this issue .

@diksha0149 You add those resources by raising another issue.
