### ISSUE TITLE
Screenshots of Working application links are broken 

### ISSUE THREAD

**Issue by mayanksharma-1** [yashikabhargava/WebX#83]
## Description
Screenshots of **Working application links** under the README.md are broken 

## Screenshots
[![Image of broken screenshots](https://i.gyazo.com/7e5dde565211a3f1c9e382235d257c29.png)](https://gyazo.com/7e5dde565211a3f1c9e382235d257c29) 
[![Image of the broken link when the screenshots are clicked](https://i.gyazo.com/b3bfa26af55b8c49330c8e0a013d22fd.jpg)](https://gyazo.com/b3bfa26af55b8c49330c8e0a013d22fd)

## Do you want to work on this issue?
yes

## How are you planning to resolve on this issue?
the src for the images is `src="img\Screenshot1.jpg"` changing it to `src="src\img\Screenshot1.jpg"` should work 

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
I've assigned this issue to you but won't be able to consider it under hacktoberfest as it's mentioned on hacktoberfest website that optimizing images won't be counted as a contribution towards hacktoberfest.
