### ISSUE TITLE
Favicon of the webpage is missing.

### ISSUE THREAD

**Issue by fosterer** [yashikabhargava/WebX#86]
## Description
An icon that appears beside the title of the website known as favicon is missing in the website title bar.

## Screenshots
Put any screenshot(s) here.

## Do you want to work on this issue?
yes

## How are you planning to resolve on this issue?
I would be providing a favicon in the index.html

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by fosterer** [comment]
please assign me this issue and a chance to contribute in this repo.

**Comment by yashikabhargava** [comment]
@fosterer favicon was added to the website but it's not working so if you are planning on adding a new one kindly remove the code for previous one.

**Comment by yashikabhargava** [comment]
Also, do ask for reviewing the favicon that you're planning on adding before opening the PR.
Thanks
