### ISSUE TITLE
Website to learn Web Development

### ISSUE THREAD

**Issue by heyvats21** [yashikabhargava/WebX#88]
## Description
want to add a different section of from where we can learn web dev

![image](https://user-images.githubusercontent.com/81029204/194717600-e0e62a77-f167-449f-9c11-c2001b7b2831.png)

## Do you want to work on this issue?
write yes 

## How are you planning to resolve on this issue?
I will do R&D on the free resources and get the proper list of it.

## Are you raising this issue under hacktoberfest?
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
Sounds good, have assigned this issue to you.

**Comment by heyvats21** [comment]
@yashikabhargava  have a look I have completed the task.
