### ISSUE TITLE
Dark Mode toogle not working

### ISSUE THREAD

**Issue by front-runner-sd** [yashikabhargava/WebX#89]
## Description
I can create a dark mode  theme for the website.

## Screenshots
Put any screenshot(s) here.

## Do you want to work on this issue?
yes

## How are you planning to resolve on this issue?
Provide some information about the changes you'll be doing to resolve the issue.

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by yashikabhargava** [comment]
@front-runner-sd The code for dark mode is there but it's not working, hence do you want to work on resolving that issue?

**Comment by front-runner-sd** [comment]
yes I want to work in this issue.

**Comment by front-runner-sd** [comment]
@yashikabhargava I've fixed the button , it is now working. But in the code the button is only on landing page so only home page changes theme.
![image](https://user-images.githubusercontent.com/91823106/194718465-8980cccd-b1fc-4b91-8be8-127295acc56f.png)

**Comment by yashikabhargava** [comment]
Okay, so will you be able to make it work for the whole website and not just the landing page?

**Comment by front-runner-sd** [comment]
yes! but to do so I have to add the toggle checkbox into other htmls too.
