### ISSUE TITLE
Add New Prototyping Tools Section

### ISSUE THREAD

**Issue by ShubhamPatil0723** [yashikabhargava/WebX#94]
## Description
Prototyping tools like figma, Penpot are used to create web prototypes from browsers. List these tools in WebX website

## Do you want to work on this issue?
yes

## How are you planning to resolve this issue?
Add new section in HTML files

## Are you raising this issue under hacktoberfest?
Yes

**Comment by yashikabhargava** [comment]
Sounds good, have assigned the issue to you.
