### ISSUE TITLE
Meta tags not configured for each page

### ISSUE THREAD

**Issue by MD-ARBAB-SAHID** [yashikabhargava/WebX#99]
## Description
All the pages have same tittle and no description and keywords.

## Do you want to work on this issue?
Yes

## How are you planning to resolve on this issue?
By adding meta tags to each page

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by MD-ARBAB-SAHID** [comment]
@yashikabhargava can you assign this to me ?

**Comment by yashikabhargava** [comment]
@MD-ARBAB-SAHID Thank you for raising this issue, have assigned it to you.
